[functions.solicitar-servicio]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.login-tecnico]
verify_jwt = false

[functions.verificar-login]
verify_jwt = false

[functions.pool-leads]
verify_jwt = false

[functions.crear-lead]
verify_jwt = false

[functions.blog-preguntas]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.nueva-era]
verify_jwt = false

[functions.registro-tecnico]
verify_jwt = false

[functions.gestion-saldo]
verify_jwt = false

[functions.aceptar-presupuesto]
verify_jwt = false

[functions.notificar-lead]
verify_jwt = false

[functions.newsletter-unsubscribe]
verify_jwt = false

[functions.verificar-email]
verify_jwt = false
