CREATE TABLE IF NOT EXISTS pageviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path text NOT NULL,
    referrer text,
    user_agent text,
    screen_width integer,
    country text,
    created_at timestamptz DEFAULT now()
);

ALTER TABLE pageviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "anon_insert" ON pageviews 
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "service_read" ON pageviews 
  FOR SELECT TO service_role USING (true);
